package UDML.dcsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_OtpType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_OtpType() {
    super(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x2438cc3b84fcd92bL, "OtpType", "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502379");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_RequiredConstructor_0 = new EnumerationDescriptor.MemberDescriptor("RequiredConstructor", "RequiredConstructor", 0x2438cc3b84fcd92cL, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502380");
  private final EnumerationDescriptor.MemberDescriptor myMember_ObjectFormConstrctor_0 = new EnumerationDescriptor.MemberDescriptor("ObjectFormConstrctor", "ObjectFormConstrctor", 0x2438cc3b84fcd92eL, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502382");
  private final EnumerationDescriptor.MemberDescriptor myMember_AutoAttributeValueGen_0 = new EnumerationDescriptor.MemberDescriptor("AutoAttributeValueGen", "AutoAttributeValueGen", 0x2438cc3b84fcd92fL, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502383");
  private final EnumerationDescriptor.MemberDescriptor myMember_LinkCountGetter_0 = new EnumerationDescriptor.MemberDescriptor("LinkCountGetter", "LinkCountGetter", 0x2438cc3b84fcd930L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502384");
  private final EnumerationDescriptor.MemberDescriptor myMember_LinkCountSetter_0 = new EnumerationDescriptor.MemberDescriptor("LinkCountSetter", "LinkCountSetter", 0x2438cc3b84fcd931L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502385");
  private final EnumerationDescriptor.MemberDescriptor myMember_LinkAdder_0 = new EnumerationDescriptor.MemberDescriptor("LinkAdder", "LinkAdder", 0x2438cc3b84fcd932L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502386");
  private final EnumerationDescriptor.MemberDescriptor myMember_LinkAdderNew_0 = new EnumerationDescriptor.MemberDescriptor("LinkAdderNew", "LinkAdderNew", 0x2438cc3b84fcd934L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502388");
  private final EnumerationDescriptor.MemberDescriptor myMember_LinkRemover_0 = new EnumerationDescriptor.MemberDescriptor("LinkRemover", "LinkRemover", 0x2438cc3b84fcd933L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502387");
  private final EnumerationDescriptor.MemberDescriptor myMember_LinkUpdater_0 = new EnumerationDescriptor.MemberDescriptor("LinkUpdater", "LinkUpdater", 0x2438cc3b84fcd935L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502389");
  private final EnumerationDescriptor.MemberDescriptor myMember_Setter_0 = new EnumerationDescriptor.MemberDescriptor("Setter", "Setter", 0x2438cc3b84fcd936L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502390");
  private final EnumerationDescriptor.MemberDescriptor myMember_Getter_0 = new EnumerationDescriptor.MemberDescriptor("Getter", "Getter", 0x2438cc3b84fcd937L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502391");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x2438cc3b84fcd92bL, 0x2438cc3b84fcd92cL, 0x2438cc3b84fcd92eL, 0x2438cc3b84fcd92fL, 0x2438cc3b84fcd930L, 0x2438cc3b84fcd931L, 0x2438cc3b84fcd932L, 0x2438cc3b84fcd934L, 0x2438cc3b84fcd933L, 0x2438cc3b84fcd935L, 0x2438cc3b84fcd936L, 0x2438cc3b84fcd937L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_RequiredConstructor_0, myMember_ObjectFormConstrctor_0, myMember_AutoAttributeValueGen_0, myMember_LinkCountGetter_0, myMember_LinkCountSetter_0, myMember_LinkAdder_0, myMember_LinkAdderNew_0, myMember_LinkRemover_0, myMember_LinkUpdater_0, myMember_Setter_0, myMember_Getter_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "RequiredConstructor":
        return myMember_RequiredConstructor_0;
      case "ObjectFormConstrctor":
        return myMember_ObjectFormConstrctor_0;
      case "AutoAttributeValueGen":
        return myMember_AutoAttributeValueGen_0;
      case "LinkCountGetter":
        return myMember_LinkCountGetter_0;
      case "LinkCountSetter":
        return myMember_LinkCountSetter_0;
      case "LinkAdder":
        return myMember_LinkAdder_0;
      case "LinkAdderNew":
        return myMember_LinkAdderNew_0;
      case "LinkRemover":
        return myMember_LinkRemover_0;
      case "LinkUpdater":
        return myMember_LinkUpdater_0;
      case "Setter":
        return myMember_Setter_0;
      case "Getter":
        return myMember_Getter_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
