package UDML.dcsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AssocType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AssocType() {
    super(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a18b32eL, "AssocType", "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/1730163904888746798");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_One2One_0 = new EnumerationDescriptor.MemberDescriptor("One2One", "One2One", 0x1802c6e79a18b32fL, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/1730163904888746799");
  private final EnumerationDescriptor.MemberDescriptor myMember_One2Many_0 = new EnumerationDescriptor.MemberDescriptor("One2Many", "One2Many", 0x1802c6e79a18b483L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/1730163904888747139");
  private final EnumerationDescriptor.MemberDescriptor myMember_Many2Many_0 = new EnumerationDescriptor.MemberDescriptor("Many2Many", "Many2Many", 0x2438cc3b84fcd939L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/2610060540067502393");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a18b32eL, 0x1802c6e79a18b32fL, 0x1802c6e79a18b483L, 0x2438cc3b84fcd939L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_One2One_0, myMember_One2Many_0, myMember_Many2Many_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "One2One":
        return myMember_One2One_0;
      case "One2Many":
        return myMember_One2Many_0;
      case "Many2Many":
        return myMember_Many2Many_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
