package UDML.dcsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AssocEndType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AssocEndType() {
    super(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a18b703L, "AssocEndType", "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/1730163904888747779");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_One_0 = new EnumerationDescriptor.MemberDescriptor("One", "One", 0x1802c6e79a18b704L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/1730163904888747780");
  private final EnumerationDescriptor.MemberDescriptor myMember_Many_0 = new EnumerationDescriptor.MemberDescriptor("Many", "Many", 0x1802c6e79a18b7b1L, "r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/1730163904888747953");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a18b703L, 0x1802c6e79a18b704L, 0x1802c6e79a18b7b1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_One_0, myMember_Many_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "One":
        return myMember_One_0;
      case "Many":
        return myMember_Many_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
