package UDML.dcsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAnnotationDcsl = createDescriptorForAnnotationDcsl();
  /*package*/ final ConceptDescriptor myConceptAssociate = createDescriptorForAssociate();
  /*package*/ final ConceptDescriptor myConceptConcernDCSL = createDescriptorForConcernDCSL();
  /*package*/ final ConceptDescriptor myConceptDAssoc = createDescriptorForDAssoc();
  /*package*/ final ConceptDescriptor myConceptDAttr = createDescriptorForDAttr();
  /*package*/ final ConceptDescriptor myConceptDClass = createDescriptorForDClass();
  /*package*/ final ConceptDescriptor myConceptDOpt = createDescriptorForDOpt();
  /*package*/ final ConceptDescriptor myConceptDomainModelDcsl = createDescriptorForDomainModelDcsl();
  /*package*/ final EnumerationDescriptor myEnumerationAssocEndType = new EnumerationDescriptor_AssocEndType();
  /*package*/ final EnumerationDescriptor myEnumerationAssocType = new EnumerationDescriptor_AssocType();
  /*package*/ final EnumerationDescriptor myEnumerationOtpType = new EnumerationDescriptor_OtpType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, "UDML.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAnnotationDcsl, myConceptAssociate, myConceptConcernDCSL, myConceptDAssoc, myConceptDAttr, myConceptDClass, myConceptDOpt, myConceptDomainModelDcsl);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AnnotationDcsl:
        return myConceptAnnotationDcsl;
      case LanguageConceptSwitch.Associate:
        return myConceptAssociate;
      case LanguageConceptSwitch.ConcernDCSL:
        return myConceptConcernDCSL;
      case LanguageConceptSwitch.DAssoc:
        return myConceptDAssoc;
      case LanguageConceptSwitch.DAttr:
        return myConceptDAttr;
      case LanguageConceptSwitch.DClass:
        return myConceptDClass;
      case LanguageConceptSwitch.DOpt:
        return myConceptDOpt;
      case LanguageConceptSwitch.DomainModelDcsl:
        return myConceptDomainModelDcsl;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationAssocEndType, myEnumerationAssocType, myEnumerationOtpType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAnnotationDcsl() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.dcsl", "AnnotationDcsl", 0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82f1ba8L);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe825L);
    b.origin("r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/9069817326574967720");
    b.version(3);
    b.alias("DCSL");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAssociate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.dcsl", "Associate", 0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a1a321cL);
    b.class_(false, false, false);
    b.origin("r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/1730163904888844828");
    b.version(3);
    b.property("cardMin", 0x1802c6e79a1a32d5L).type(PrimitiveTypeId.INTEGER).origin("1730163904888845013").done();
    b.property("cardMax", 0x1802c6e79a1a332eL).type(PrimitiveTypeId.INTEGER).origin("1730163904888845102").done();
    b.associate("type", 0x1802c6e79a1a357aL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L).optional(true).origin("1730163904888845690").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConcernDCSL() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.dcsl", "ConcernDCSL", 0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82cea89L);
    b.class_(false, false, false);
    // extends: UDML.core.structure.Concern
    b.super_(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe82cL);
    b.origin("r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/9069817326574824073");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDAssoc() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.dcsl", "DAssoc", 0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a18b4cfL);
    b.class_(false, false, false);
    // extends: UDML.dcsl.structure.AnnotationDcsl
    b.super_(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82f1ba8L);
    b.origin("r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/1730163904888747215");
    b.version(3);
    b.property("ascType", 0x1802c6e79a18b66bL).type(MetaIdFactory.dataTypeId(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a18b32eL)).origin("1730163904888747627").done();
    b.property("endType", 0x1802c6e79a18b807L).type(MetaIdFactory.dataTypeId(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a18b703L)).origin("1730163904888748039").done();
    b.property("dependsOn", 0x1802c6e79a18b878L).type(PrimitiveTypeId.BOOLEAN).origin("1730163904888748152").done();
    b.property("derivedFrom", 0x1802c6e79a18b918L).type(PrimitiveTypeId.BOOLEAN).origin("1730163904888748312").done();
    b.aggregate("associate", 0x1802c6e79a1bc5eeL).target(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a1a321cL).optional(true).ordered(true).multiple(true).origin("1730163904888948206").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDAttr() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.dcsl", "DAttr", 0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82c4f33L);
    b.class_(false, false, false);
    // extends: UDML.dcsl.structure.AnnotationDcsl
    b.super_(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82f1ba8L);
    b.origin("r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/9069817326574784307");
    b.version(3);
    b.property("id", 0x7dde76cdf82c4f35L).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784309").done();
    b.property("type", 0x7dde76cdf82c4f36L).type(PrimitiveTypeId.STRING).origin("9069817326574784310").done();
    b.property("auto", 0x7dde76cdf82c4f37L).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784311").done();
    b.property("autoIncrement", 0x7dde76cdf82c4f38L).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784312").done();
    b.property("unique", 0x7dde76cdf82c4f39L).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784313").done();
    b.property("mutable", 0x7dde76cdf82c4f3aL).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784314").done();
    b.property("optional", 0x7dde76cdf82c4f3bL).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784315").done();
    b.property("lenght", 0x7dde76cdf82c4f3cL).type(PrimitiveTypeId.INTEGER).origin("9069817326574784316").done();
    b.property("min", 0x7dde76cdf82c4f3dL).type(PrimitiveTypeId.INTEGER).origin("9069817326574784317").done();
    b.property("max", 0x7dde76cdf82c4f3fL).type(PrimitiveTypeId.INTEGER).origin("9069817326574784319").done();
    b.property("serialisable", 0x7dde76cdf82c4f40L).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784320").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDClass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.dcsl", "DClass", 0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82c4f43L);
    b.class_(false, false, false);
    // extends: UDML.dcsl.structure.AnnotationDcsl
    b.super_(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82f1ba8L);
    b.origin("r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/9069817326574784323");
    b.version(3);
    b.property("serialisable", 0x7dde76cdf82c4f45L).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784325").done();
    b.property("mutable", 0x7dde76cdf82c4f46L).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784326").done();
    b.property("singleton", 0x7dde76cdf82c4f47L).type(PrimitiveTypeId.BOOLEAN).origin("9069817326574784327").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDOpt() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.dcsl", "DOpt", 0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82c4f49L);
    b.class_(false, false, false);
    // extends: UDML.dcsl.structure.AnnotationDcsl
    b.super_(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82f1ba8L);
    b.origin("r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/9069817326574784329");
    b.version(3);
    b.property("requires", 0x7dde76cdf82c4f4aL).type(PrimitiveTypeId.STRING).origin("9069817326574784330").done();
    b.property("effect", 0x7dde76cdf82c4f4bL).type(PrimitiveTypeId.STRING).origin("9069817326574784331").done();
    b.property("type", 0x7dde76cdf82c4f4cL).type(MetaIdFactory.dataTypeId(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x2438cc3b84fcd92bL)).origin("9069817326574784332").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainModelDcsl() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.dcsl", "DomainModelDcsl", 0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82f1baeL);
    b.class_(false, false, false);
    // extends: UDML.core.structure.DomainModel
    b.super_(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe830L);
    b.origin("r:29e2b064-c406-47a3-bf14-e704f820f577(UDML.dcsl.structure)/9069817326574967726");
    b.version(3);
    return b.create();
  }
}
