package UDML.dcsl.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Associate_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new DAssoc_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new DAttr_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new DClass_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new DOpt_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a1a321cL), MetaIdFactory.conceptId(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x1802c6e79a18b4cfL), MetaIdFactory.conceptId(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82c4f33L), MetaIdFactory.conceptId(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82c4f43L), MetaIdFactory.conceptId(0xa7f6d256248949efL, 0xa2047e72e8fb22eeL, 0x7dde76cdf82c4f49L)).seal();
}
