package UDML.core.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class MemberEnd_SubstituteMenu extends SubstituteMenuBase {
  public MemberEnd_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for MemberEnd. Generated from implicit smart reference attribute.", new SNodePointer("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)", "4183952400186618829")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_uhi27v_a(), CONCEPTS.MemberEnd$6e));
    result.add(new SMP_Subconcepts_uhi27v_b());
    return result;
  }

  public class SMP_ReferenceScope_uhi27v_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_uhi27v_a() {
      super(CONCEPTS.MemberEnd$6e, LINKS.MemberEnd$addv, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_uhi27v_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_uhi27v_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "MemberEnd", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.MemberEnd$6e);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MemberEnd$6e = MetaAdapterFactory.getConcept(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x3a10628a5a4433cdL, "UDML.core.structure.MemberEnd");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink MemberEnd$addv = MetaAdapterFactory.getReferenceLink(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x3a10628a5a4433cdL, 0x3a10628a5a4433d0L, "MemberEnd");
  }
}
