package UDML.core.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class RefAnnotation_SubstituteMenu extends SubstituteMenuBase {
  public RefAnnotation_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for RefAnnotation. Generated from implicit smart reference attribute.", new SNodePointer("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)", "1730163904889536847")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_oot5l7_a(), CONCEPTS.RefAnnotation$5Z));
    result.add(new SMP_Subconcepts_oot5l7_b());
    return result;
  }

  public class SMP_ReferenceScope_oot5l7_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_oot5l7_a() {
      super(CONCEPTS.RefAnnotation$5Z, LINKS.Annotation$Pkrw, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_oot5l7_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_oot5l7_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "RefAnnotation", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.RefAnnotation$5Z);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept RefAnnotation$5Z = MetaAdapterFactory.getConcept(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x1802c6e79a24c14fL, "UDML.core.structure.RefAnnotation");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink Annotation$Pkrw = MetaAdapterFactory.getReferenceLink(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x1802c6e79a24c14fL, 0x1802c6e79a24c25bL, "Annotation");
  }
}
