package UDML.agl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_ActivityGraph;
  private ConceptPresentation props_AnnotationAgl;
  private ConceptPresentation props_ConcernAgl;
  private ConceptPresentation props_DomainModelAgl;
  private ConceptPresentation props_Edge;
  private ConceptPresentation props_Node;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.ActivityGraph:
        if (props_ActivityGraph == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ActivityGraph = cpb.create();
        }
        return props_ActivityGraph;
      case LanguageConceptSwitch.AnnotationAgl:
        if (props_AnnotationAgl == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AnnotationAgl = cpb.create();
        }
        return props_AnnotationAgl;
      case LanguageConceptSwitch.ConcernAgl:
        if (props_ConcernAgl == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ConcernAgl = cpb.create();
        }
        return props_ConcernAgl;
      case LanguageConceptSwitch.DomainModelAgl:
        if (props_DomainModelAgl == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DomainModelAgl = cpb.create();
        }
        return props_DomainModelAgl;
      case LanguageConceptSwitch.Edge:
        if (props_Edge == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Edge");
          props_Edge = cpb.create();
        }
        return props_Edge;
      case LanguageConceptSwitch.Node:
        if (props_Node == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Node");
          props_Node = cpb.create();
        }
        return props_Node;
    }
    return null;
  }
}
