package UDML.agl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ActivityGraph = 0;
  public static final int AnnotationAgl = 1;
  public static final int ConcernAgl = 2;
  public static final int DomainModelAgl = 3;
  public static final int Edge = 4;
  public static final int Node = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe56b0c6677af410cL, 0x8fbc5e675905259aL);
    builder.put(0x46a234f7a469f760L, ActivityGraph);
    builder.put(0x3a10628a5a3e4622L, AnnotationAgl);
    builder.put(0x3a10628a5a3e4614L, ConcernAgl);
    builder.put(0x3a10628a5a3e4621L, DomainModelAgl);
    builder.put(0x46a234f7a469f764L, Edge);
    builder.put(0x46a234f7a469f763L, Node);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
