package UDML.agl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActivityGraph = createDescriptorForActivityGraph();
  /*package*/ final ConceptDescriptor myConceptAnnotationAgl = createDescriptorForAnnotationAgl();
  /*package*/ final ConceptDescriptor myConceptConcernAgl = createDescriptorForConcernAgl();
  /*package*/ final ConceptDescriptor myConceptDomainModelAgl = createDescriptorForDomainModelAgl();
  /*package*/ final ConceptDescriptor myConceptEdge = createDescriptorForEdge();
  /*package*/ final ConceptDescriptor myConceptNode = createDescriptorForNode();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, "UDML.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActivityGraph, myConceptAnnotationAgl, myConceptConcernAgl, myConceptDomainModelAgl, myConceptEdge, myConceptNode);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ActivityGraph:
        return myConceptActivityGraph;
      case LanguageConceptSwitch.AnnotationAgl:
        return myConceptAnnotationAgl;
      case LanguageConceptSwitch.ConcernAgl:
        return myConceptConcernAgl;
      case LanguageConceptSwitch.DomainModelAgl:
        return myConceptDomainModelAgl;
      case LanguageConceptSwitch.Edge:
        return myConceptEdge;
      case LanguageConceptSwitch.Node:
        return myConceptNode;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActivityGraph() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.agl", "ActivityGraph", 0xe56b0c6677af410cL, 0x8fbc5e675905259aL, 0x46a234f7a469f760L);
    b.class_(false, false, false);
    // extends: UDML.agl.structure.AnnotationAgl
    b.super_(0xe56b0c6677af410cL, 0x8fbc5e675905259aL, 0x3a10628a5a3e4622L);
    b.origin("r:7bf40b3f-b05e-4365-ac0a-102a95323498(UDML.agl.structure)/5089688767102056288");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnnotationAgl() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.agl", "AnnotationAgl", 0xe56b0c6677af410cL, 0x8fbc5e675905259aL, 0x3a10628a5a3e4622L);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe825L);
    b.origin("r:7bf40b3f-b05e-4365-ac0a-102a95323498(UDML.agl.structure)/4183952400186230306");
    b.version(3);
    b.alias("AGL");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConcernAgl() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.agl", "ConcernAgl", 0xe56b0c6677af410cL, 0x8fbc5e675905259aL, 0x3a10628a5a3e4614L);
    b.class_(false, false, false);
    // extends: UDML.core.structure.Concern
    b.super_(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe82cL);
    b.origin("r:7bf40b3f-b05e-4365-ac0a-102a95323498(UDML.agl.structure)/4183952400186230292");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainModelAgl() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.agl", "DomainModelAgl", 0xe56b0c6677af410cL, 0x8fbc5e675905259aL, 0x3a10628a5a3e4621L);
    b.class_(false, false, false);
    // extends: UDML.core.structure.DomainModel
    b.super_(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe830L);
    b.origin("r:7bf40b3f-b05e-4365-ac0a-102a95323498(UDML.agl.structure)/4183952400186230305");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEdge() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.agl", "Edge", 0xe56b0c6677af410cL, 0x8fbc5e675905259aL, 0x46a234f7a469f764L);
    b.class_(false, false, false);
    b.origin("r:7bf40b3f-b05e-4365-ac0a-102a95323498(UDML.agl.structure)/5089688767102056292");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.agl", "Node", 0xe56b0c6677af410cL, 0x8fbc5e675905259aL, 0x46a234f7a469f763L);
    b.class_(false, false, false);
    b.origin("r:7bf40b3f-b05e-4365-ac0a-102a95323498(UDML.agl.structure)/5089688767102056291");
    b.version(3);
    return b.create();
  }
}
