package UDML.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ParameterDirectionKind extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ParameterDirectionKind() {
    super(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef95L, "ParameterDirectionKind", "r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298645");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_dr1_0 = new EnumerationDescriptor.MemberDescriptor("dr1", "Drect1", 0x49e02d1c64bbef96L, "r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298646");
  private final EnumerationDescriptor.MemberDescriptor myMember_dr2_0 = new EnumerationDescriptor.MemberDescriptor("dr2", "Drict2", 0x49e02d1c64bbef97L, "r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298647");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef95L, 0x49e02d1c64bbef96L, 0x49e02d1c64bbef97L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_dr1_0, myMember_dr2_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "dr1":
        return myMember_dr1_0;
      case "dr2":
        return myMember_dr2_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
