package UDML.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAggregation = createDescriptorForAggregation();
  /*package*/ final ConceptDescriptor myConceptAnnotable = createDescriptorForAnnotable();
  /*package*/ final ConceptDescriptor myConceptAnnotation = createDescriptorForAnnotation();
  /*package*/ final ConceptDescriptor myConceptAssociation = createDescriptorForAssociation();
  /*package*/ final ConceptDescriptor myConceptClass = createDescriptorForClass();
  /*package*/ final ConceptDescriptor myConceptClassifier = createDescriptorForClassifier();
  /*package*/ final ConceptDescriptor myConceptComposition = createDescriptorForComposition();
  /*package*/ final ConceptDescriptor myConceptConcern = createDescriptorForConcern();
  /*package*/ final ConceptDescriptor myConceptDataType = createDescriptorForDataType();
  /*package*/ final ConceptDescriptor myConceptDomainModel = createDescriptorForDomainModel();
  /*package*/ final ConceptDescriptor myConceptEnumeration = createDescriptorForEnumeration();
  /*package*/ final ConceptDescriptor myConceptGeneralization = createDescriptorForGeneralization();
  /*package*/ final ConceptDescriptor myConceptMemberEnd = createDescriptorForMemberEnd();
  /*package*/ final ConceptDescriptor myConceptOperation = createDescriptorForOperation();
  /*package*/ final ConceptDescriptor myConceptPackage = createDescriptorForPackage();
  /*package*/ final ConceptDescriptor myConceptParameter = createDescriptorForParameter();
  /*package*/ final ConceptDescriptor myConceptPrimitiveType = createDescriptorForPrimitiveType();
  /*package*/ final ConceptDescriptor myConceptProperty = createDescriptorForProperty();
  /*package*/ final ConceptDescriptor myConceptRefAnnotation = createDescriptorForRefAnnotation();
  /*package*/ final ConceptDescriptor myConceptRelationShip = createDescriptorForRelationShip();
  /*package*/ final EnumerationDescriptor myEnumerationParameterDirectionKind = new EnumerationDescriptor_ParameterDirectionKind();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAggregation, myConceptAnnotable, myConceptAnnotation, myConceptAssociation, myConceptClass, myConceptClassifier, myConceptComposition, myConceptConcern, myConceptDataType, myConceptDomainModel, myConceptEnumeration, myConceptGeneralization, myConceptMemberEnd, myConceptOperation, myConceptPackage, myConceptParameter, myConceptPrimitiveType, myConceptProperty, myConceptRefAnnotation, myConceptRelationShip);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Aggregation:
        return myConceptAggregation;
      case LanguageConceptSwitch.Annotable:
        return myConceptAnnotable;
      case LanguageConceptSwitch.Annotation:
        return myConceptAnnotation;
      case LanguageConceptSwitch.Association:
        return myConceptAssociation;
      case LanguageConceptSwitch.Class:
        return myConceptClass;
      case LanguageConceptSwitch.Classifier:
        return myConceptClassifier;
      case LanguageConceptSwitch.Composition:
        return myConceptComposition;
      case LanguageConceptSwitch.Concern:
        return myConceptConcern;
      case LanguageConceptSwitch.DataType:
        return myConceptDataType;
      case LanguageConceptSwitch.DomainModel:
        return myConceptDomainModel;
      case LanguageConceptSwitch.Enumeration:
        return myConceptEnumeration;
      case LanguageConceptSwitch.Generalization:
        return myConceptGeneralization;
      case LanguageConceptSwitch.MemberEnd:
        return myConceptMemberEnd;
      case LanguageConceptSwitch.Operation:
        return myConceptOperation;
      case LanguageConceptSwitch.Package:
        return myConceptPackage;
      case LanguageConceptSwitch.Parameter:
        return myConceptParameter;
      case LanguageConceptSwitch.PrimitiveType:
        return myConceptPrimitiveType;
      case LanguageConceptSwitch.Property:
        return myConceptProperty;
      case LanguageConceptSwitch.RefAnnotation:
        return myConceptRefAnnotation;
      case LanguageConceptSwitch.RelationShip:
        return myConceptRelationShip;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationParameterDirectionKind);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAggregation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Aggregation", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x7dde76cdf827246aL);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x7dde76cdf7e6f65bL);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/9069817326574445674");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnnotable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Annotable", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524296738");
    b.version(3);
    b.aggregate("annotation", 0x1802c6e79a24d4d1L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x1802c6e79a24c14fL).optional(true).ordered(true).multiple(true).origin("1730163904889541841").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Annotation", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe825L);
    b.interface_();
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524296741");
    b.version(3);
    b.associate("target", 0x49e02d1c64bbe828L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L).optional(false).origin("5323304359524296744").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAssociation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Association", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef9dL);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x7dde76cdf7e6f65bL);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298653");
    b.version(3);
    b.alias("association");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Class", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef7fL);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298623");
    b.version(3);
    b.aggregate("ownedOperation", 0x49e02d1c64bbef89L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef87L).optional(true).ordered(true).multiple(true).origin("5323304359524298633").done();
    b.aggregate("ownedAttribute", 0x49e02d1c64bbef8aL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef86L).optional(true).ordered(true).multiple(true).origin("5323304359524298634").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassifier() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Classifier", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L);
    b.interface_();
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524296756");
    b.version(3);
    b.associate("specialization", 0x49e02d1c64bbef77L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef75L).optional(true).origin("5323304359524298615").done();
    b.aggregate("generalization", 0x49e02d1c64bbef76L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef75L).optional(true).ordered(true).multiple(true).origin("5323304359524298614").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComposition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Composition", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x7dde76cdf80bb07aL);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x7dde76cdf7e6f65bL);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/9069817326572646522");
    b.version(3);
    b.alias("composition");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConcern() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Concern", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe82cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524296748");
    b.version(3);
    b.aggregate("annotation", 0x49e02d1c64bbe82eL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe825L).optional(true).ordered(true).multiple(true).origin("5323304359524296750").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "DataType", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbefa4L);
    b.class_(false, true, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298660");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "DomainModel", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe830L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524296752");
    b.version(3);
    b.aggregate("element", 0x49e02d1c64bbe832L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L).optional(true).ordered(true).multiple(true).origin("5323304359524296754").done();
    b.aggregate("concern", 0x49e02d1c64bbe833L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe82cL).optional(true).ordered(true).multiple(true).origin("5323304359524296755").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnumeration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Enumeration", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbefa7L);
    b.class_(false, false, false);
    // extends: UDML.core.structure.DataType
    b.super_(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbefa4L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298663");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGeneralization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Generalization", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef75L);
    b.class_(false, false, false);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298613");
    b.version(3);
    b.associate("specific", 0x49e02d1c64bbef78L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L).optional(false).origin("5323304359524298616").done();
    b.associate("general", 0x2599e98ad164bdfL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L).optional(false).origin("169340839579241439").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMemberEnd() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "MemberEnd", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x3a10628a5a4433cdL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/4183952400186618829");
    b.version(3);
    b.property("role", 0x3a10628a5a4433cfL).type(PrimitiveTypeId.STRING).origin("4183952400186618831").done();
    b.associate("MemberEnd", 0x3a10628a5a4433d0L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L).optional(false).origin("4183952400186618832").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOperation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Operation", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef87L);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298631");
    b.version(3);
    b.aggregate("ownedParameter", 0x49e02d1c64bbef9cL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef94L).optional(true).ordered(true).multiple(true).origin("5323304359524298652").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPackage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Package", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef7aL);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298618");
    b.version(3);
    b.aggregate("classifier", 0x49e02d1c64bbef7cL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L).optional(true).ordered(true).multiple(true).origin("5323304359524298620").done();
    b.aggregate("package", 0x49e02d1c64bbef7dL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef7aL).optional(true).ordered(true).multiple(true).origin("5323304359524298621").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Parameter", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef94L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298644");
    b.version(3);
    b.property("direction", 0x49e02d1c64bbef98L).type(MetaIdFactory.dataTypeId(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef95L)).origin("5323304359524298648").done();
    b.associate("type", 0x49e02d1c64bbef99L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L).optional(false).origin("5323304359524298649").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPrimitiveType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "PrimitiveType", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbefa8L);
    b.class_(false, false, false);
    // extends: UDML.core.structure.DataType
    b.super_(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbefa4L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298664");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProperty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "Property", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbef86L);
    b.class_(false, false, false);
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe822L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/5323304359524298630");
    b.version(3);
    b.associate("type", 0x49e02d1c64bbef9fL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L).optional(false).origin("5323304359524298655").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRefAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "RefAnnotation", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x1802c6e79a24c14fL);
    b.class_(false, false, false);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/1730163904889536847");
    b.version(3);
    b.associate("Annotation", 0x1802c6e79a24c25bL).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe825L).optional(false).origin("1730163904889537115").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRelationShip() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UDML.core", "RelationShip", 0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x7dde76cdf7e6f65bL);
    b.interface_();
    b.parent(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x49e02d1c64bbe834L);
    b.origin("r:364988e2-6287-4edf-be31-15c02c2e0d7a(UDML.core.structure)/9069817326572646401");
    b.version(3);
    b.aggregate("MemberEndSource", 0x3a10628a5a4433d1L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x3a10628a5a4433cdL).optional(false).ordered(true).multiple(false).origin("4183952400186618833").done();
    b.aggregate("MemberEndTarget", 0x3a10628a5a4433d2L).target(0xfd381d931dce4228L, 0xba53a4e0ecaf0da2L, 0x3a10628a5a4433cdL).optional(false).ordered(true).multiple(false).origin("4183952400186618834").done();
    return b.create();
  }
}
