package UDML.diagram.shapes.Shapes;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import de.itemis.mps.editor.diagram.runtime.shape.IShapeStyle;
import java.awt.geom.GeneralPath;

public class Arrow extends AbstractShape {

  private double relativeHeight;

  public Arrow(double relativeHeight) {
    this.relativeHeight = relativeHeight;
  }




  @Override
  protected void draw(final Graphics2D graphics, final Rectangle2D bounds, IShapeStyle style) {
    GeneralPath shape = new GeneralPath();
    double width = bounds.getWidth();
    double height = bounds.getHeight();
    double x = bounds.getX();
    double y = bounds.getY();
    double x2 = x + width;
    double centerY = y + height / 2;
    double leftX = x2 - height * this.relativeHeight;
    shape.moveTo(leftX, centerY - height * this.relativeHeight);
    shape.lineTo(x2, centerY);
    shape.lineTo(leftX, centerY + height * this.relativeHeight);
    graphics.draw(shape);
  }

}
