package UDML.diagram.shapes.Shapes;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import de.itemis.mps.editor.diagram.runtime.shape.IShapeStyle;
import java.awt.geom.GeneralPath;

public class DiamondHead extends AbstractShape {

  private double relativeHeight;
  private boolean filled;

  public DiamondHead(double relativeHeight, boolean filled) {
    this.relativeHeight = relativeHeight;
    this.filled = filled;
  }




  @Override
  protected void draw(final Graphics2D graphics, final Rectangle2D bounds, IShapeStyle style) {
    GeneralPath shape = new GeneralPath();
    double width = bounds.getWidth();
    double height = bounds.getHeight();
    double x = bounds.getX();
    double y = bounds.getY();
    double x2 = x + width;
    double centerY = y + height / 2;
    double centerX = x + width / 2;
    shape.moveTo(centerX, centerY - height * this.relativeHeight);
    shape.lineTo(x2, centerY);
    shape.lineTo(centerX, centerY + height * this.relativeHeight);
    shape.lineTo(x, centerY);
    shape.closePath();
    bounds.setRect(x, y, width - height * this.relativeHeight, height);
    bounds.setFrame(x, y, width - height * this.relativeHeight, height);

    if (this.filled) {
      graphics.fill(shape);
    } else {
      graphics.draw(shape);
    }

  }

}
